### PR TITLE
Upgrade to aws-sdk-go-v2 and Go 1.16

### PR DESCRIPTION
**Pull request by dtjm**
Interesting changes from the aws-sdk-go v1:

1. There is no need to instantiate `session` when creating a client, only `aws.Config` 
2. No interfaces are provided in the package, so interfaces for mocking are now defined in this repo

Resolves https://github.com/jniebuhr/aws-pca-issuer/issues/4

### CODE REVIEW

**Comment by anbaig** [comment]
Looks like the unit test failed
```test.go:42: failed to sts.GetCallerIdentity: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 200415e7-0488-4101-b802-8a57211a152e, api error InvalidClientTokenId: The security token included in the request is invalid. -- []```

Probably just need to add a mock for STS GetCallerIdentity call, similar to the mocks for the PCA clients

**Comment by dtjm** [comment]
It might be easier to add a flag for testing and skip the `sts.GetCallerIdentity` call during tests.  I don't think mocking out will provide any benefit since it's a pretty simple code flow.  Would you be ok with that?

**Comment by anbaig** [comment]
After taking a closer look, it seems that making that STS call isn't actually necessary and more for logging the caller identity (I assume for debugging)? In that case a flag makes sense to me.

**Comment by anbaig** [comment]
Ran the integration test locally on this commit and it looks like it all passed. The PR looks good to me!

**Pull request merged**
