### PR TITLE
Return cert + chain in tls.crt and root CA in ca.crt

### PR DESCRIPTION
**Pull request by pabrahamsson**
This change will put the requested certificate and the intermediate certificate chain into `tls.crt` and the root CA certificate in `ca.crt`. This is an attempt to follow the cert-manager [Certificate documentation](https://cert-manager.io/docs/concepts/certificate/) for where certificates should be expected within the secret.

These changes have been successfully tested on OpenShift 4.7.x.

### CODE REVIEW

**Comment by jniebuhr** [comment]
Thanks for your PR. We've added in unit tests as of today, can you please rebase your branch?

**Comment by pabrahamsson** [comment]
Absolutely, my branch should now be in sync with master.

**Comment by pabrahamsson** [comment]
I'll take a look at the failed test(s) and update accordingly

**Comment by pabrahamsson** [comment]
@jniebuhr my changes will require valid PEM encoded certificates in the unit tests for them to pass. I can see if I can provide some dummy cert/CAs but wanted to check with you first.

**Comment by jniebuhr** [comment]
Yes, that works for me. Just some self signed cert should do the trick.

**Comment by pabrahamsson** [comment]
@jniebuhr I've updated the PR to include the following three certs
- rootCA: `subject=C = US, ST = Some-State, L = MyCity, O = Company Ltd, OU = IT, CN = domain.com`
- intCA: `subject=C = US, ST = Some-State, O = Company Ltd, OU = IT, CN = int.domain.com`
- cert: `subject=C = US, ST = Some-State, L = MyCity, CN = foo.domain.com`

The `cert` is signed by `intCA` which in turn was issued by `rootCA`.
I've changed the unit test to expect `Sign()` to return `cert + intCA + "\n", rootCA + "\n"`

**Pull request merged**
